rango/urls.py
from unicodedata import name
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    #如果匹配到'' 那么调用views.index, index是对view的convention
    path('about/', views.about, name='about'),
    #如果匹配到about/,那么调用about界面

    #slug变量用来mapping, 由show_category view传
    path('category/<slug:category_name_slug>/',views.show_category, name='show_category'),

    path('add_category/', views.add_category, name='add_category'),

    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    #让所有以rango/开头的URL交由rango来处理
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rango/models.py
from distutils.command.upload import upload
from tabnanny import verbose
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    #name = models.CharField(max_length=128, unique=True)
    NAME_MAX_LENGTH = 128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    # one to many
    #category = models.ForeignKey(Category, on_delete=models.CASCADE)
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # 链接Userprofile类和UserModel
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # 额外属性
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms, views
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    # name = forms.CharField(max_length=128,
    #                        help_text="Please enter the category name.")
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # 给form提供额外信息的内部类
    class Meta:
        #提供ModelForm和Model之间的关联
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    # title = forms.CharField(max_length=128,
    #                         help_text="Please enter the title of the page.")
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        
        #可以选择在form中包含的fields，用exclude去除某个filed,他允许NULL值
        exclude = ('category',)
        #或者include某个filed
        #fields = ('title', 'url', 'views')
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from audioop import reverse
from cgitb import html
import profile
from re import A
from django.shortcuts import redirect, render
from django.urls import reverse


from django.template import context
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from datetime import datetime

def index(request):

    #query 数据库中的categories,按降序排列top5,将list放在context字典中
    category_list = Category.objects.order_by('-likes')[:5]
    #query pages, 选取top5
    pages_list = Page.objects.order_by('-views')[:5]

    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    # 将模板变量名template variable 映射到python变量, 存在dict数据结构中

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = pages_list

# Call the helper function to handle the cookies
    visitor_cookie_handler(request)


    #context_dict['visits'] = request.session['visits']

    #request.session.set_test_cookie()
    #获取response object
    response = render(request, 'rango/index.html', context=context_dict)
    

    return response


    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.

    #####return render(request,'rango/index.html',context=context_dict)
    
    #render函数接收用户的request, 模板html文件和 context键值对字典
    #return HttpResponse("Rango says hey there partner!<a href='/rango/about/'>About</a>")
    


def about(request):
    #return HttpResponse("Rango says here is the about page.<a href='/rango/'>Index</a>")

    context_dict = {}


    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    #cookie session
    # if request.session.test_cookie_worked():
    #     print("TEST COOKIE WORKED!")
    #     request.session.delete_test_cookie()

    response = render(request, 'rango/about.html', context=context_dict)
    return response

#用来添加新page给每个category
def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass to the template rendering engine.
    # 创建context字典来传给template引擎
    context_dict = {}

    try:
        #是否能找到所给名字的category name slug?
        #如果找不到,the .get() method raises a DoesNotExist exception.
        #如果找到,get返回实例model
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        #遍历所有相关page,使用filter
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages

        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        #同时将cat实例从数据库加载到context字典中,可以用来在template中证实cat存在
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    #是否是http POST请求
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        #form 是否有效？
        if form.is_valid():
            cat = form.save(commit=True)
            print (cat,cat.slug)
            return redirect('/rango/')
            #返回网页
        else:
            print(form.errors)
    return render(request,'rango/add_category.html', {'form':form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    #检查cate是否存在
    if category is None:
        return redirect('/rango/')
    
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category',
                                        kwargs = {'category_name_slug':
                                                  category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category':category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    # bool值 注册是否成功
    registered = False

    if request.method == 'POST':
        #尝试从生表格中收集数据
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            #如果valid 储存数据
            user = user_form.save()

            #hash password, update user object
            user.set_password(user.password)
            user.save()

            #sort out the userprofile instance
            #commit=false 来推迟model储存
            profile = profile_form.save(commit=False)
            profile.user = user

            #上传图片
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save

            registered = True
        else:
            #不可用表格
            print(user_form.errors, profile_form.errors)
    else:
        #如果不是HTTP POST请求,空白表格
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'rango/register.html',
                           context={'user_form': user_form,
                                    'profile_form': profile_form,
                                    'registered': registered})
def user_login(request):
    if request.method == 'POST':
        #收集从用户提供的用户名密码,通过login表单
        username = request.POST.get('username')
        password = request.POST.get('password')

        #用django自带的机制检查用户密码对,返回obj
        user = authenticate(username=username,password=password)

        # 如果得到了user obj 那么正确
        # 如果没得到obj, None 找不到user
        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('rango:index'))
            else:
                #非活跃用户
                return HttpResponse("Your Rango account is disabled.")
        else:
            # 提供信息不正确
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    #如果不是http request请求, 展示登录表格
    #这种场景很可能是HTTP get
    else:
        return render(request, 'rango/login.html')
    

@login_required
def restricted(request):
    #return HttpResponse("Since you're logged in, you can see this text!")
    return render(request, 'rango/restricted.html')

# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

# a helper method 取得cookie
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

#并不是一个view 只是helper函数 不反回response object
# handle cookie
def visitor_cookie_handler(request):
    #获取visit次数, 用COOKIES.GET 获得

    visits = int(get_server_side_cookie(request, 'visits','1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))

    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # 如果距离上次访问超过一天
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    request.session['visits'] = visits

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
   About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page. <br />
        <strong>This tutorial has been put together by Yufei Bai</strong><br />
    </div>
    <div>
        <p>Visits: {{ visits }}</p>
    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /><br/> <!-- New line -->   
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <form id="category_form" method="post" action="/rango/add_category/">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Category" />
    </form>
{% endblock %}
    

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
<h1>Add a Page</h1>
<div>
    <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Page" />
    </form>
</div>
{% endblock %}
    

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html>
    <head>
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <!-- Show these links when the user is logged in -->
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li> 
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                {% else %}
                    <!-- Show these links when the user is NOT logged in -->
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}
                    <!-- Outside the conditional statements, ALWAYS show -->
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>    
            </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li>
            <strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong>
            </li>
            {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}


{% block body_block %}
    {% if category %}   
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}

    {% if user.is_authenticated %} 
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% endif%} 

    {% else %}
    The specified category does not exist.
    {% endif %}

{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        {% if user.is_authenticated %}
        howdy {{ user.username }}!
        {% else %}
        hey there partner!
        {% endif %}
        <strong>{{ boldmessage }}</strong>
    </div>

    <h2>Most Liked Categories</h2>

    <div>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li>
                <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong>
    {% endif %}
    </div>

    <h2>Most Viewed Pages</h2>

    <div>
    {% if pages %}
        <ul>
        {% for page in pages %} 
            <li>
                <a href="{{ page.url }}">{{ page.title }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <strong>There are no pages present.</strong>
    {% endif %}
    </div>

    <div>

        <img src="{% static 'images/rango.jpg' %}"
            alt = "Picture of Rango">

    </div>
    
    
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %} 
    Restricted Page 
{% endblock %}

{% block body_block %} 
Since you're logged in, you can see this text!
{% endblock %}